[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
thiserror = "2.0.20"                             # error handling
regex = "1.11.1"
# 18.x needs home 0.5.12, which requires rustc 1.88. CodeCrafters uses 1.87.
rustyline = "17.0.2"
home = "=0.5.11"